// samples/aspire-with-javascript/AspireJavaScript.React/src/components/App.js
import { useCallback, useEffect, useState } from "react";
import {
  CloudSun,
  Snowflake,
  Wind,
  CloudSnow,
  CloudFog,
  Sun,
  SunHorizon,
  ThermometerHot,
  Fire,
  ArrowsClockwise,
  Lightning,
} from "@phosphor-icons/react";
import styles from "./App.module.css";

const SUMMARY_ICONS = {
  Freezing: Snowflake,
  Bracing: Wind,
  Chilly: CloudSnow,
  Cool: CloudFog,
  Mild: CloudSun,
  Warm: Sun,
  Balmy: SunHorizon,
  Hot: ThermometerHot,
  Sweltering: Fire,
  Scorching: Fire,
};

function summaryIcon(summary) {
  const Icon = SUMMARY_ICONS[summary] ?? CloudSun;
  return <Icon size={18} weight="bold" aria-hidden="true" />;
}

function tempColor(c) {
  if (typeof c !== "number") return "var(--nb-muted)";
  if (c < -5) return "var(--nb-cold)";
  if (c < 6) return "var(--nb-cool)";
  if (c < 19) return "var(--nb-mild)";
  if (c < 31) return "var(--nb-warm)";
  return "var(--nb-hot)";
}

function App() {
  const [forecasts, setForecasts] = useState([]);
  const [state, setState] = useState("loading");

  const requestWeather = useCallback(async () => {
    setState("loading");
    try {
      const response = await fetch("api/weatherforecast");
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      const data = await response.json();
      setForecasts(Array.isArray(data) ? data : []);
      setState("ready");
    } catch (err) {
      console.error("Failed to load weather forecast", err);
      setState("error");
    }
  }, []);

  useEffect(() => {
    requestWeather();
  }, [requestWeather]);

  const status =
    state === "loading"
      ? "Loading the latest forecast…"
      : state === "error"
        ? "Couldn't reach the weather service. Try again."
        : `Showing the next ${forecasts.length} days.`;

  return (
    <>
      <a className={styles.skip} href="#forecast">
        Skip to forecast
      </a>
      <div className={styles.page}>
        <header className={styles.banner}>
          <span className={styles.logo} aria-hidden="true">
            <CloudSun size={34} weight="fill" />
          </span>
          <span className={styles.brandText}>
            <span className={styles.kicker}>Aspire · React + Webpack</span>
            <h1 className={styles.title}>
              React <em>Weather</em>
            </h1>
          </span>
          <span className={styles.stampWrap}>
            <span className={styles.stamp}>
              <Lightning size={14} weight="fill" aria-hidden="true" />
              Live API
            </span>
          </span>
        </header>

        <main id="forecast" className={styles.main}>
          <section className={styles.card} aria-labelledby="forecast-title">
            <div className={styles.cardHead}>
              <h2 id="forecast-title" className={styles.cardTitle}>
                5-Day Forecast
              </h2>
              <button
                type="button"
                className={styles.refresh}
                onClick={requestWeather}
                disabled={state === "loading"}
              >
                <ArrowsClockwise
                  size={18}
                  weight="bold"
                  aria-hidden="true"
                  className={state === "loading" ? styles.spin : undefined}
                />
                {state === "loading" ? "Loading" : "Refresh"}
              </button>
            </div>

            <p
              className={`${styles.status} ${state === "error" ? styles.statusError : ""}`}
              role="status"
              aria-live="polite"
            >
              {status}
            </p>

            <div className={styles.tableWrap}>
              <table className={styles.table}>
                <caption>Randomly generated weather forecast data.</caption>
                <thead>
                  <tr>
                    <th scope="col">Date</th>
                    <th scope="col">Temp. (°C)</th>
                    <th scope="col">Temp. (°F)</th>
                    <th scope="col">Summary</th>
                  </tr>
                </thead>
                <tbody>
                  {forecasts.length === 0 ? (
                    <tr>
                      <td className={styles.dateCell}>—</td>
                      <td>—</td>
                      <td>—</td>
                      <td>
                        {state === "loading" ? "Loading…" : "No forecasts"}
                      </td>
                    </tr>
                  ) : (
                    forecasts.map((w) => (
                      <tr key={w.date}>
                        <td className={styles.dateCell}>{w.date}</td>
                        <td>
                          <span className={styles.temp}>
                            <span
                              className={styles.dot}
                              style={{ background: tempColor(w.temperatureC) }}
                              aria-hidden="true"
                            />
                            {w.temperatureC}°
                          </span>
                        </td>
                        <td>
                          <span className={styles.temp}>{w.temperatureF}°</span>
                        </td>
                        <td>
                          <span className={styles.summaryCell}>
                            <span className={styles.chipIcon}>
                              {summaryIcon(w.summary)}
                            </span>
                            <span className={styles.summaryLabel}>
                              {w.summary}
                            </span>
                          </span>
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          </section>

          <p className={styles.foot}>
            <Lightning size={16} weight="fill" aria-hidden="true" />
            Powered by <strong>Aspire</strong> — same data, four personalities.
          </p>
        </main>
      </div>
    </>
  );
}

export default App;

// samples/aspire-with-javascript/AspireJavaScript.Angular/src/app/app.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  OnInit,
  inject,
  signal,
} from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { MatToolbarModule } from '@angular/material/toolbar';
import { MatCardModule } from '@angular/material/card';
import { MatTableModule } from '@angular/material/table';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule, MatIconRegistry } from '@angular/material/icon';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { WeatherForecasts } from '../types/weatherForecast';

type LoadState = 'loading' | 'ready' | 'error';

const SUMMARY_ICONS: Record<string, string> = {
  Freezing: 'severe_cold',
  Bracing: 'air',
  Chilly: 'weather_snowy',
  Cool: 'cloud',
  Mild: 'partly_cloudy_day',
  Warm: 'sunny',
  Balmy: 'clear_day',
  Hot: 'device_thermostat',
  Sweltering: 'local_fire_department',
  Scorching: 'whatshot',
};

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    MatToolbarModule,
    MatCardModule,
    MatTableModule,
    MatButtonModule,
    MatIconModule,
    MatProgressBarModule,
  ],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent implements OnInit {
  protected readonly title = 'weather';
  protected readonly forecasts = signal<WeatherForecasts>([]);
  protected readonly state = signal<LoadState>('loading');
  protected readonly displayedColumns = [
    'date',
    'temperatureC',
    'temperatureF',
    'summary',
  ] as const;

  private readonly http = inject(HttpClient);

  constructor(iconRegistry: MatIconRegistry) {
    // Render every <mat-icon> with the Material Symbols (outlined) font.
    iconRegistry.setDefaultFontSetClass('material-symbols-outlined');
  }

  ngOnInit(): void {
    this.load();
  }

  load(): void {
    this.state.set('loading');
    this.http.get<WeatherForecasts>('api/weatherforecast').subscribe({
      next: (result) => {
        this.forecasts.set(result ?? []);
        this.state.set('ready');
      },
      error: (err) => {
        console.error('Failed to load weather forecast', err);
        this.state.set('error');
      },
    });
  }

  protected summaryIcon(summary: string): string {
    return SUMMARY_ICONS[summary] ?? 'thermostat';
  }

  protected tempTone(celsius: number): string {
    if (celsius < -5) return 'cold';
    if (celsius < 6) return 'cool';
    if (celsius < 19) return 'mild';
    if (celsius < 31) return 'warm';
    return 'hot';
  }

  protected get statusText(): string {
    switch (this.state()) {
      case 'loading':
        return 'Loading the latest forecast…';
      case 'error':
        return 'Could not load the forecast. Select refresh to try again.';
      default:
        return `Showing a ${this.forecasts().length}-day forecast.`;
    }
  }
}

<a class="skip-link" href="#forecast">Skip to forecast</a>

<div class="brand-stripe" aria-hidden="true"></div>

<header class="masthead">
  <span class="brand-mark" aria-hidden="true">
    <mat-icon>partly_cloudy_day</mat-icon>
  </span>
  <span class="brand-text">
    <span class="brand-eyebrow">Aspire · Angular</span>
    <h1 class="masthead-title"><span class="brand-accent">Angular</span> Weather</h1>
  </span>
  <button
    mat-flat-button
    class="refresh"
    type="button"
    (click)="load()"
    [disabled]="state() === 'loading'"
    [attr.aria-label]="state() === 'loading' ? 'Refreshing forecast' : 'Refresh forecast'"
  >
    <mat-icon aria-hidden="true" [class.spin]="state() === 'loading'">refresh</mat-icon>
    <span class="refresh-label">{{ state() === 'loading' ? 'Refreshing' : 'Refresh' }}</span>
  </button>
</header>
<section class="learning-banner">
  <h2>My Angular + .NET Aspire Learning Project</h2>
  <p>This application is running locally from my GitHub fork.</p>
</section>
<main id="forecast" class="page" [attr.aria-busy]="state() === 'loading'">
  <section class="forecast" aria-labelledby="forecast-heading">
    <div class="forecast-head">
      <p class="eyebrow">Five-day outlook</p>
      <h2 id="forecast-heading" class="forecast-title">Weather forecast</h2>
    </div>

    <div class="progress-rail" aria-hidden="true">
      @if (state() === 'loading') {
        <mat-progress-bar mode="indeterminate"></mat-progress-bar>
      }
    </div>

    <p class="status" role="status" aria-live="polite">{{ statusText }}</p>

    @if (state() === 'error') {
      <div class="notice">
        <span class="notice-icon" aria-hidden="true"><mat-icon>cloud_off</mat-icon></span>
        <p class="notice-text">We couldn’t reach the weather service right now.</p>
        <button mat-stroked-button type="button" class="notice-retry" (click)="load()">
          <mat-icon aria-hidden="true">refresh</mat-icon>
          Try again
        </button>
      </div>
    } @else if (lead(); as featured) {
      <article class="hero" aria-labelledby="hero-day">
        <div class="hero-when">
          <p class="hero-eyebrow">Featured day</p>
          <h3 id="hero-day" class="hero-day">{{ weekday(featured.date) }}</h3>
          <p class="hero-date">{{ calendarDate(featured.date) }}</p>
          <p class="hero-summary">{{ featured.summary }}</p>
        </div>
        <div class="hero-figure">
          <span class="hero-figure-icon" aria-hidden="true">
            <mat-icon>{{ summaryIcon(featured.summary) }}</mat-icon>
          </span>
          <p class="hero-temp">
            <span class="hero-temp-c">{{ featured.temperatureC }}<span class="deg">°</span></span>
            <span class="hero-temp-f">{{ featured.temperatureF }}°F</span>
          </p>
        </div>
      </article>

      <ul class="forecast-grid">
        @for (day of rest(); track day.date; let i = $index) {
          <li class="grid-item" [style.--i]="i">
            <article class="day" [attr.aria-labelledby]="'day-' + i + '-name'">
              <header class="day-head">
                <h3 class="day-name" [id]="'day-' + i + '-name'">{{ shortWeekday(day.date) }}</h3>
                <p class="day-date">{{ calendarDate(day.date) }}</p>
              </header>
              <span class="day-icon" [attr.data-tone]="tempTone(day.temperatureC)" aria-hidden="true">
                <mat-icon>{{ summaryIcon(day.summary) }}</mat-icon>
              </span>
              <dl class="day-stats">
                <div class="stat">
                  <dt class="visually-hidden">Temperature</dt>
                  <dd class="day-temp">
                    <span class="day-temp-c">{{ day.temperatureC }}°</span>
                    <span class="day-temp-f">{{ day.temperatureF }}°F</span>
                  </dd>
                </div>
                <div class="stat">
                  <dt class="visually-hidden">Conditions</dt>
                  <dd class="day-summary">{{ day.summary }}</dd>
                </div>
              </dl>
            </article>
          </li>
        }
      </ul>
    } @else if (state() === 'loading') {
      <div class="hero skeleton" aria-hidden="true"></div>
      <ul class="forecast-grid" aria-hidden="true">
        @for (slot of [1, 2, 3, 4]; track slot) {
          <li class="grid-item"><div class="day skeleton"></div></li>
        }
      </ul>
    } @else {
      <p class="empty">No forecast data is available right now.</p>
    }
  </section>

  <p class="byline">
    <mat-icon aria-hidden="true">bolt</mat-icon>
    Powered by <strong>Aspire</strong>
  </p>
</main>
